{"name": "Test Case 3: Login con usuario y contraseña incorrectos", "status": "passed", "description": "Verifica que se muestre el mensaje de error al intentar loguearse con credenciales inválidas.", "steps": [{"name": "Navegar a la página principal", "status": "passed", "start": 1756735256073, "stop": 1756735258667}, {"name": "Hacer click en 'Signup / Login'", "status": "passed", "start": 1756735258667, "stop": 1756735259770}, {"name": "Verificar que aparece 'Login to your account'", "status": "passed", "start": 1756735259770, "stop": 1756735259908}, {"name": "Ingresar email inválido 'vangrachel@example.com' y password inválido", "status": "passed", "start": 1756735259908, "stop": 1756735260126}, {"name": "Hacer click en 'Login'", "status": "passed", "start": 1756735260126, "stop": 1756735261107}, {"name": "Verificar que se muestra el mensaje de error", "status": "passed", "start": 1756735261107, "stop": 1756735261245}], "start": 1756735256071, "stop": 1756735261245, "uuid": "cf97693d-5ef2-4111-bf71-db50973726b8", "historyId": "ccb423b204ecd653142f428549d17c6a", "testCaseId": "ccb423b204ecd653142f428549d17c6a", "fullName": "tests.test_auth#test_login_user_with_incorrect_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "gianfranco-h81h3m4"}, {"name": "thread", "value": "13164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}], "titlePath": ["tests", "test_auth.py"]}