{"name": "Test Case 3: Login con usuario y contraseña incorrectos", "status": "passed", "description": "Verifica que se muestre el mensaje de error al intentar loguearse con credenciales inválidas.", "steps": [{"name": "Navegar a la página principal", "status": "passed", "start": 1756734527099, "stop": 1756734529805}, {"name": "Hacer click en 'Signup / Login'", "status": "passed", "start": 1756734529805, "stop": 1756734531281}, {"name": "Verificar que aparece 'Login to your account'", "status": "passed", "start": 1756734531281, "stop": 1756734531312}, {"name": "Ingresar email inválido 'freemanray@example.org' y password inválido", "status": "passed", "start": 1756734531312, "stop": 1756734531752}, {"name": "Hacer click en 'Login'", "status": "passed", "start": 1756734531753, "stop": 1756734532748}, {"name": "Verificar que se muestra el mensaje de error", "status": "passed", "start": 1756734532748, "stop": 1756734532777}], "start": 1756734527096, "stop": 1756734532778, "uuid": "2f304f10-d918-4923-b765-fb121f610236", "historyId": "ccb423b204ecd653142f428549d17c6a", "testCaseId": "ccb423b204ecd653142f428549d17c6a", "fullName": "tests.test_auth#test_login_user_with_incorrect_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "gianfranco-h81h3m4"}, {"name": "thread", "value": "8495-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}], "titlePath": ["tests", "test_auth.py"]}